Sejfy mats dla organizacji
MrucznikRolePlay/Mrucznik-RP-gamemode pull request #429
Opened 2024-02-18 20:32 UTC by wiger3

Sejfy na mats w banku na kontach organizacji. Przyda się np. gunshopom

Zmiany mysql (prosze o nich nie zapomniec xd):
```sql
ALTER TABLE `mru_sejfy` ADD `mats` INT NOT NULL AFTER `kasa`;
```

2024-02-23 01:23 UTC, gumbalowsky requested changes

2024-02-23 01:23 UTC, gumbalowsky commented on gamemodes/dialogs/OnDialogResponse.pwn
> +					PlayerInfo[playerid][pAccount] += kasa;
brakuje zamiany na `DajKase(playerid)`/ `ZabierzKase(playerid)` zamiast operacji na samej zmiennej

2024-02-23 20:45 UTC, wiger3 commented on gamemodes/dialogs/OnDialogResponse.pwn
> +					PlayerInfo[playerid][pAccount] += kasa;
to zawsze tak dzialalo ze kasa leciala na konto bankowe. `DajKase` dziala na gotowce

2024-02-24 15:24 UTC, Mrucznik approved these changes

2024-02-24 15:24 UTC, merged