Komenda /ip5
MrucznikRolePlay/Mrucznik-RP-gamemode pull request #463
Opened 2024-03-23 17:28 UTC by nikodembanan

Dodanie komendy /ip5, pozwalającej na wyświetlanie 5 ostatnich adresów IP, z których korzystał gracz pod danym nickiem (nie jest zachowywane po restarcie serwa).

2024-03-23 21:31 UTC, Wallens commented
Może zastąpić obecną komendę `/ip` tą nową komendą? Ona agreguje w sobie obecne działanie, nie wymaga chyba innych uprawnień, a zawsze to trochę kodu mniej w projekcie.
Plus można dla jasności dorzucić informację, czy numer 1 oznacza najświeższe IP, czy najstarsze

2024-03-23 21:54 UTC, nikodembanan commented
> Może zastąpić obecną komendę `/ip` tą nową komendą? Ona agreguje w sobie obecne działanie, nie wymaga chyba innych uprawnień, a zawsze to trochę kodu mniej w projekcie. Plus można dla jasności dorzucić informację, czy numer 1 oznacza najświeższe IP, czy najstarsze

Można i jedno i drugie, zgadzam się, może pan dodać?

2024-03-23 22:53 UTC, Mrucznik requested changes
Dzięki za implementacje tej komendy, ale będą potrzebne zmiany.

2024-03-23 22:53 UTC, Mrucznik commented on gamemodes/modules/listaip/listaip_callbacks.pwn
> +hook OnPlayerConnect(playerid)
raczej interesują nas tylko ip'ki z których gracz się zalogował

2024-03-23 23:34 UTC, nikodembanan commented on gamemodes/modules/listaip/listaip_callbacks.pwn
> +hook OnPlayerConnect(playerid)
A przy omijaniu logowania ewentualnym się nie przyda? Albo przy tym blokowaniu wejścia na serwer dla adminów?

2024-03-24 05:04 UTC, Mrucznik commented on gamemodes/modules/listaip/listaip_callbacks.pwn
> +hook OnPlayerConnect(playerid)
okl

2024-03-24 05:05 UTC, Mrucznik approved these changes

2024-03-24 05:07 UTC, merged