Zmiany w złodzieju aut 23.03
MrucznikRolePlay/Mrucznik-RP-gamemode pull request #464
Opened 2024-03-23 17:36 UTC by nikodembanan

Zmiany umotywowane odzewem od graczy i potrzebą dostosowania zarobków do ryb. Jak przewidywałem w pierwszym PR, złodziej okazuje się być słabszym źródłem zarobku niż ryby w obecnym wydaniu.

Co zmieniono:
- zwiększenie liczby aut deluxe do 5;
- zwiększenie części "za model" zarobków za zwykłe auta o około 2/3;
- zwiększenie krótkiego czasu GPS za zwykłe auta do 45 sekund;
- zmniejszenie czasu GPS za auta deluxe do 6 minut;
- dodanie Faggio do ukradnięcia w pobliżu odległych od LS dziupli, by było jak wrócić - skuterki respawnują się po 3 minutach bez kierowcy;
- ułatwienie głównie dla złodziei z niskim skillem - szansa na powodzenie /kradnij zależy teraz od modelu wozu.

2024-03-23 21:17 UTC, Wallens commented on gamemodes/system/funkcje.pwn
> +        	id = AddCar(i);
```suggestion
			id = AddCar(i);
```

2024-03-23 21:19 UTC, Wallens commented on gamemodes/system/funkcje.pwn
> +		col2 = 1;
Może ustawiać to jako wartość domyślną argumentu funkcji? Wtedy ten if nie będzie potrzebny

2024-03-23 21:26 UTC, Wallens commented on gamemodes/commands/cmd/kradnij.pwn
> +				#if defined _ZLODZIEJ_AUT
Tak z ciekawości jaka potrzeba kryje się za stosowaniem takiej dyrektywy?

2024-03-23 21:49 UTC, nikodembanan commented on gamemodes/system/funkcje.pwn
> +		col2 = 1;
A można, trafna uwaga, może pan to zrobić?

2024-03-23 21:51 UTC, nikodembanan commented on gamemodes/commands/cmd/kradnij.pwn
> +				#if defined _ZLODZIEJ_AUT
A proszę się nie interesować!

A tak na serio to dzięki temu jak się wywali moduł złodzieja to się mapa będzie dalej kompilować. Jak gdzieś w kodzie poza modułem coś wstawiam, to staram się tam taką dyrektywę robić (ale czasem zapominam xD).

2024-03-23 23:02 UTC, Mrucznik requested changes

2024-03-23 23:02 UTC, Mrucznik commented on gamemodes/system/funkcje.pwn
> +//FUNKCJE DLA CA£EGO SERWERA
wygląda, jakby popsuło się kodowanie w tym pliku

2024-03-24 00:21 UTC, nikodembanan commented on gamemodes/system/funkcje.pwn
> +//FUNKCJE DLA CA£EGO SERWERA
waleń rozwalił

2024-03-24 00:29 UTC, nikodembanan commented on gamemodes/system/funkcje.pwn
> +//FUNKCJE DLA CA£EGO SERWERA
naprawione

2024-03-24 02:12 UTC, Mrucznik approved these changes

2024-03-24 02:12 UTC, merged